### ISSUE TITLE
JDK download page get fails with infinite redirect

### ISSUE THREAD

**Issue by onitake** [ansiblebit/oracle-java#58] opened 2017-09-25 14:40 UTC
It's not possible to use this role on CentOS due to the following error:
```
TASK [oracle-java : get latest JDK download page]
fatal: [host.domain]: FAILED! => {"changed": false, "connection": "close", "content": "", "content_length": "0", "date": "Mon, 25 Sep 2017 14:27:36 GMT", "failed": true, "location": "http://www.oracle.com/splash/www/fw_error.html?referenceerror=18.c3a7f7c1.1506349656.7e17de8&referer=http://www.oracle.com/splash/www/fw_error.html", "msg": "Status code was not [200]: HTTP Error 302: The HTTP server returned a redirect error that would lead to an infinite loop.\nThe last 30x error message was:\nMoved Temporarily", "redirected": false, "server": "AkamaiGHost", "status": 302, "url": "http://www.oracle.com/technetwork/java/javase/downloads/index.html"}
```

I tried modifying the user agent, but that did not help. Probably because they have some kind of automatic blacklisting?
Is there anything I can do to avoid this problem?

**Comment by steenzout** [comment] 2017-09-26 15:00
@onitake I don't really work with CentOS on a daily basis so I haven't encountered this problem (yet).

I'll run some tests tonight or tomorrow (no promise).

**Comment by steenzout** [comment] 2018-08-19 06:04
@onitake I cannot reproduce this problem.

lmk if this is still an issue.

in the meantime, I'm closing this issue.

**Closed as completed by steenzout** 2018-08-19 06:04 UTC
Labels: support

**Comment by onitake** [comment] 2018-08-23 15:07
I cannot reproduce the problem any more either.

Perhaps Oracle changed something on their download servers.
