### ISSUE TITLE
Failing at task "get latest JDK download page"

### ISSUE THREAD

**Issue by adithyamenon** [ansiblebit/oracle-java#84] opened 2018-06-04 13:26 UTC
"msg": "Status code was 403 and not [200]: HTTP Error 403: Forbidden", "pragma": "no-cache", "redirected": false, "server": "Apache", "status": 403, "url": "http://www.oracle.com/technetwork/java/javase/downloads/index.html"

Tried doing a curl and wget on the same URL provided but it still gave the "HTPP Error 403".

Broken links need to be fixed on subsequent tasks.

**Comment by steenzout** [comment] 2018-06-06 20:04
@adithyamenon this seems a connectivity problem between the machine you are trying to run the role against and Oracle.

**Comment by psharkey** [comment] 2018-07-30 00:51
I’ve seen the same problem several times and it’s not connectivity issue but rather a problem on Oracle’s side - 
[403: Forbidden example](https://github.com/ansiblebit/oracle-java/files/2239375/Text.File.txt)

**Comment by steenzout** [comment] 2018-08-19 06:03
I cannot reproduce this problem.

Closing for now.

**Closed as completed by steenzout** 2018-08-19 06:03 UTC
